// <auto-generated />
using System;
using HealthFlow.Services.Patients.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthFlow.Services.Patients.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    partial class PatientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthFlow.Services.Patients.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Patients_CreatedAt");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_Patients_LastName");

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Patients_MedicalRecordNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Patients_Status");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76d735f9-d9a8-4d74-a15a-29abe043e66d"),
                            CreatedAt = new DateTime(2025, 10, 15, 6, 46, 51, 625, DateTimeKind.Utc).AddTicks(4350),
                            DateOfBirth = new DateTime(1980, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe",
                            MedicalRecordNumber = "MRN001",
                            Status = "Admitted"
                        },
                        new
                        {
                            Id = new Guid("0f327691-eb68-4de9-96b4-7c12928f7fd7"),
                            CreatedAt = new DateTime(2025, 10, 16, 6, 46, 51, 625, DateTimeKind.Utc).AddTicks(4360),
                            DateOfBirth = new DateTime(1975, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Smith",
                            MedicalRecordNumber = "MRN002",
                            Status = "InTreatment"
                        },
                        new
                        {
                            Id = new Guid("38691ef6-b8a7-4a63-9576-46b1858801f2"),
                            CreatedAt = new DateTime(2025, 10, 17, 2, 46, 51, 625, DateTimeKind.Utc).AddTicks(5110),
                            DateOfBirth = new DateTime(1990, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            LastName = "Johnson",
                            MedicalRecordNumber = "MRN003",
                            Status = "Critical"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
